#!/bin/bash

# Script pour générer le fichier AUTHORS

# Définir le nom du fichier AUTHORS
AUTHORS_FILE="AUTHORS"

# En-tête du fichier
HEADER="# File @generated by hack/generate-authors.sh. DO NOT EDIT."
HEADER="$HEADER\n# This file lists all contributors to the repository."
HEADER="$HEADER\n# See hack/generate-authors.sh to make modifications."

# Récupérer la liste des auteurs uniques et triée
AUTHORS_LIST=$(git log --format='%an <%ae>' | sort -u)

# Écrire l'en-tête et la liste des auteurs dans le fichier
echo "$HEADER" > "$AUTHORS_FILE"
echo "$AUTHORS_LIST" >> "$AUTHORS_FILE"

echo "Le fichier $AUTHORS_FILE a été généré avec succès."

exit 0
